export const patients = [
	{
		_id: 1,
		fname: "Juliette",
		lname: "Andromeda Mao",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 2,
		fname: "Klaes",
		lname: "Ashford",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 3,
		fname: "Chrisjen",
		lname: "Avasarala",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 4,
		fname: "Amos",
		lname: "Burton",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 5,
		fname: "Michael",
		lname: "Carter",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 6,
		fname: "Anderson",
		lname: "Dawes",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 7,
		fname: "Roberta",
		lname: "Draper",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 8,
		fname: "Camina",
		lname: "Drummer",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 9,
		fname: "Winston",
		lname: "Duarte",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 10,
		fname: "James",
		lname: "Holden",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 11,
		fname: "Marcos",
		lname: "Inaros",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 12,
		fname: "Fred",
		lname: "Johnson",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 13,
		fname: "Alex",
		lname: "Kamal",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 14,
		fname: "Josephus",
		lname: "Miller",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
	{
		_id: 15,
		fname: "Naomi",
		lname: "Nagata",
		telephone: "999-999-9999",
		email: "name@host.net",
		dob: "1990, 10, 01",
		address: "123 Fake St",
		city: "Corvallis",
		state: "OR",
		zip: "99999",
	},
]

export const records = [
	{
		_id: 1,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 2,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 3,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 4,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 5,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 6,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 7,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 8,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
	{
		_id: 9,
		patientId: "671597f127580d1002ee6c39",
		apptDate: "2023-10-01T19:30:00.000+00:00",
		notes: "Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque Lorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisqueLorem ipsum odor amet, consectetuer adipiscing elit. Interdum quisque",
	},
]
